import streamlit as st
import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision import models, transforms
from PIL import Image, ImageEnhance
import numpy as np
import cv2
import pandas as pd
import time
import os
from fpdf import FPDF

# --- CONFIGURATION ---
MODEL_PATH = "neuroguard_model.pth"
CLASSES = ['Glioma', 'Meningioma', 'No Tumor', 'Pituitary']

# --- PAGE CONFIG ---
st.set_page_config(
    page_title="NeuroGuard Pro",
    page_icon="🧠",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- SESSION STATE ---
if 'page' not in st.session_state:
    st.session_state['page'] = 'dashboard'
if 'analysis_result' not in st.session_state:
    st.session_state['analysis_result'] = None
if 'report_ready' not in st.session_state:
    st.session_state['report_ready'] = False
if 'current_report_path' not in st.session_state:
    st.session_state['current_report_path'] = ""

# --- DARK MEDICAL THEME CSS ---
def apply_custom_style():
    st.markdown("""
        <style>
        @import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@300;500;700&display=swap');
        
        .stApp {
            background: linear-gradient(to bottom right, #0f172a, #1e293b);
            color: #f8fafc;
            font-family: 'Plus Jakarta Sans', sans-serif;
        }
        [data-testid="stSidebar"] {
            background-color: #020617;
            border-right: 1px solid #1e293b;
        }
        div[data-testid="stMetric"] {
            background: rgba(30, 41, 59, 0.7);
            border: 1px solid rgba(148, 163, 184, 0.2);
            border-radius: 12px;
            padding: 15px;
            backdrop-filter: blur(10px);
        }
        .stButton>button {
            background: linear-gradient(90deg, #0ea5e9 0%, #2563eb 100%);
            color: white;
            border: none;
            border-radius: 8px;
            height: 3em;
            font-weight: 600;
        }
        h1, h2, h3 { color: #f8fafc; }
        .gradient-text {
            background: -webkit-linear-gradient(0deg, #38bdf8, #818cf8);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }
        </style>
    """, unsafe_allow_html=True)

# --- PROFESSIONAL PDF GENERATOR ---
class PDFReport(FPDF):
    def header(self):
        # Letterhead
        self.set_font('Arial', 'B', 20)
        self.cell(0, 10, 'NEUROGUARD DIAGNOSTICS', 0, 1, 'C')
        self.set_font('Arial', '', 10)
        self.cell(0, 5, 'Center for Advanced Neural Imaging & AI Analysis', 0, 1, 'C')
        self.cell(0, 5, 'Chengalpattu, Tamil Nadu, India | Ref: NG-2026-XAI', 0, 1, 'C')
        self.ln(5)
        self.set_line_width(0.5)
        self.line(10, 35, 200, 35)
        self.ln(10)

    def footer(self):
        self.set_y(-25)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 5, 'This report was generated by an AI Diagnostic Support System.', 0, 1, 'C')
        self.cell(0, 5, 'It is not a substitute for professional medical advice. Verify with histopathology.', 0, 1, 'C')
        self.cell(0, 5, f'Page {self.page_no()}', 0, 0, 'R')

    def chapter_title(self, label):
        self.set_font('Arial', 'B', 12)
        self.set_fill_color(200, 220, 255)
        self.cell(0, 8, f"  {label}", 0, 1, 'L', True)
        self.ln(4)

    def chapter_body(self, text):
        self.set_font('Arial', '', 11)
        self.multi_cell(0, 6, text)
        self.ln()

# --- MODEL LOGIC ---
class GradCAM:
    def __init__(self, model, target_layer):
        self.model = model
        self.target_layer = target_layer
        self.gradients = None
        self.activations = None
        self.hooks = []
        self._register_hooks()

    def _register_hooks(self):
        def forward_hook(module, input, output):
            self.activations = output
        def backward_hook(module, grad_input, grad_output):
            self.gradients = grad_output[0]
        self.hooks.append(self.target_layer.register_forward_hook(forward_hook))
        self.hooks.append(self.target_layer.register_full_backward_hook(backward_hook))

    def generate_heatmap(self, input_tensor, class_idx):
        output = self.model(input_tensor)
        self.model.zero_grad()
        output[0, class_idx].backward()
        weights = torch.mean(self.gradients, dim=(2, 3), keepdim=True)
        cam = torch.sum(weights * self.activations, dim=1).squeeze()
        cam = F.relu(cam)
        cam -= cam.min()
        cam /= (cam.max() + 1e-7)
        return cam.detach().cpu().numpy()

    def remove_hooks(self):
        for hook in self.hooks:
            hook.remove()

@st.cache_resource
def load_model():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = models.resnet18(weights=None)
    model.fc = nn.Linear(model.fc.in_features, len(CLASSES))
    if not os.path.exists(MODEL_PATH):
        return None, device
    try:
        model.load_state_dict(torch.load(MODEL_PATH, map_location=device))
    except Exception:
        return None, device
    model.to(device)
    model.eval()
    return model, device

def preprocess_image(image):
    transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])
    return transform(image).unsqueeze(0)

# ==========================================
# PAGE 1: DASHBOARD
# ==========================================
def show_dashboard():
    # Sidebar
    with st.sidebar:
        st.markdown("### 🧠 NeuroGuard Pro")
        st.caption("v5.0 | Clinical Edition")
        st.markdown("---")
        # Cool "Cyber Brain" Icon
       # --- LOGO CHANGE HERE ---
        # Rod of Asclepius (Snake & Stick) - Professional Medical Symbol
        st.image("https://cdn-icons-png.flaticon.com/512/4006/4006511.png", width=80)
        st.markdown("Dr. Aashiq Ahamed ")
        st.caption("Chief Neurologist")
        st.markdown("---")
        st.success("✅ System Online")
        st.info("🚀 GPU Active")

    # Main Header
    st.markdown("# <span class='gradient-text'>Diagnostic Workstation</span>", unsafe_allow_html=True)
    st.markdown("AI-Assisted Neural Anomaly Detection")
    st.write("")

    col_left, col_right = st.columns([1, 2], gap="large")

    with col_left:
        st.markdown("#### 📥 Scan Input")
        uploaded_file = st.file_uploader("Upload MRI (DICOM/JPG)", type=["jpg", "jpeg", "png"])
        
        if uploaded_file:
            # Image Processing
            img = Image.open(uploaded_file).convert('RGB')
# ... inside show_dashboard ...
            with st.expander("🛠️ Image Enhancement (Clinical Calibration)", expanded=False):
                # OLD: contrast = st.slider("Contrast", 0.5, 2.0, 1.0, 0.1)
                
                # NEW: Tighter "Safe" Limits (0.8 to 1.2)
                contrast = st.slider("Contrast Adjustment", 0.8, 1.2, 1.0, 0.05)
                brightness = st.slider("Brightness Adjustment", 0.8, 1.2, 1.0, 0.05)
                
                # Visual Warning if they go too far
                if contrast > 1.1 or brightness > 1.1:
                    st.caption("⚠️ Note: High contrast/brightness may mask subtle tumor textures.")

                enhancer = ImageEnhance.Contrast(img)
                img = enhancer.enhance(contrast)
                enhancer = ImageEnhance.Brightness(img)
                img = enhancer.enhance(brightness)
            st.image(img, caption="Process View", use_container_width=True)
            img.save("temp_scan.jpg") 

    with col_right:
        model, device = load_model()
        
        if uploaded_file and model:
            st.markdown("#### 🧬 Analysis Protocol")
            
            if st.button("RUN DIAGNOSTIC ALGORITHM"):
                with st.spinner('Synchronizing Neural Layers...'):
                    time.sleep(1.2)
                    input_tensor = preprocess_image(img).to(device)
                    with torch.no_grad():
                        output = model(input_tensor)
                        probs = F.softmax(output, dim=1)[0]
                        conf, pred_idx = torch.max(probs, 0)
                    
                    target_layer = model.layer4[-1]
                    gcam = GradCAM(model, target_layer)
                    heatmap = gcam.generate_heatmap(input_tensor, pred_idx)
                    gcam.remove_hooks()
                    
                    st.session_state['analysis_result'] = {
                        'prediction': CLASSES[pred_idx],
                        'confidence': f"{conf.item()*100:.1f}",
                        'probs': probs.tolist(),
                        'heatmap': heatmap
                    }

            if st.session_state['analysis_result']:
                res = st.session_state['analysis_result']
                c1, c2, c3 = st.columns(3)
                c1.metric("Detection", res['prediction'])
                c2.metric("Confidence", f"{res['confidence']}%")
                c3.metric("Urgency", "HIGH" if res['prediction'] != "No Tumor" else "LOW")
                
                st.markdown("---")
                v1, v2 = st.columns(2)
                img_np = np.array(img.resize((224, 224)))
                heatmap_res = cv2.resize(res['heatmap'], (224, 224))
                heatmap_color = cv2.applyColorMap(np.uint8(255 * heatmap_res), cv2.COLORMAP_JET)
                heatmap_color = cv2.cvtColor(heatmap_color, cv2.COLOR_BGR2RGB)
                superimposed = np.uint8(heatmap_color * 0.4 + img_np * 0.6)
                
                with v1:
                    st.markdown("**Attention Map**")
                    st.image(superimposed, use_container_width=True, clamp=True)
                with v2:
                    st.markdown("**Probability Graph**")
                    chart_data = pd.DataFrame({'Condition': CLASSES, 'Probability': res['probs']})
                    st.bar_chart(chart_data, x='Condition', y='Probability', color="#38bdf8", horizontal=True)

                st.markdown("---")
                if st.button("📄 GENERATE CLINICAL REPORT"):
                    st.session_state['page'] = 'report'
                    st.session_state['report_ready'] = False
                    st.rerun()
        elif not model:
            st.error("⚠️ Model Weights Not Found.")

# ==========================================
# PAGE 2: PROFESSIONAL REPORT
# ==========================================
def show_report_page():
    st.markdown("# 📄 Report Generation")
    
    if not st.session_state['analysis_result']:
        st.warning("No analysis found.")
        if st.button("Back"):
            st.session_state['page'] = 'dashboard'
            st.rerun()
        return

    res = st.session_state['analysis_result']
    
    with st.form("report_form"):
        st.markdown("### 1. Patient Demographics")
        c1, c2, c3 = st.columns(3)
        p_name = c1.text_input("Patient Name", "") # Default to you for demo? Or blank.
        p_id = c2.text_input("Patient ID (MRN)", "NG-9921")
        p_age = c3.text_input("Age / Gender", "24 / M")
        
        c4, c5 = st.columns(2)
        p_ref = c4.text_input("Referring Physician", "Dr. Gokul S")
        p_date = c5.date_input("Exam Date")
        
        st.markdown("### 2. Clinical Findings")
        comments = st.text_area("Radiologist Interpretation", height=150)
        
        submitted = st.form_submit_button("Generate Lab report")

    if submitted:
        pdf = PDFReport()
        pdf.add_page()
        
        # --- PATIENT BLOCK ---
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 8, "PATIENT INFORMATION", 0, 1)
        pdf.set_font("Arial", '', 11)
        # Draw a box around info
        start_y = pdf.get_y()
        pdf.cell(95, 8, f"Name: {p_name}", 1, 0)
        pdf.cell(95, 8, f"ID: {p_id}", 1, 1)
        pdf.cell(95, 8, f"Age/Gender: {p_age}", 1, 0)
        pdf.cell(95, 8, f"Date: {p_date}", 1, 1)
        pdf.cell(190, 8, f"Ref. Physician: {p_ref}", 1, 1)
        pdf.ln(8)
        
        # --- SCAN IMAGE ---
        pdf.chapter_title("SCAN ACQUISITION")
        if os.path.exists("temp_scan.jpg"):
            # Center the image
            pdf.image("temp_scan.jpg", x=65, w=80)
            pdf.ln(5)
        
        # --- FINDINGS ---
        pdf.chapter_title("DIAGNOSTIC FINDINGS")
        pdf.set_font("Arial", 'B', 11)
        pdf.cell(40, 8, "Primary Detection:", 0, 0)
        pdf.set_font("Arial", '', 11)
        pdf.cell(0, 8, res['prediction'], 0, 1)
        
        pdf.set_font("Arial", 'B', 11)
        pdf.cell(40, 8, "AI Confidence:", 0, 0)
        pdf.set_font("Arial", '', 11)
        pdf.cell(0, 8, f"{res['confidence']}%", 0, 1)
        pdf.ln(5)
        
        pdf.set_font("Arial", 'B', 11)
        pdf.cell(0, 8, "Radiological Impression:", 0, 1)
        pdf.set_font("Arial", '', 11)
        pdf.multi_cell(0, 6, comments)
        pdf.ln(15)
        
        # --- SIGNATURE ---
        pdf.line(120, pdf.get_y(), 190, pdf.get_y()) # Line
        pdf.set_xy(120, pdf.get_y() + 2)
        pdf.set_font("Arial", 'B', 10)
        pdf.cell(70, 5, "Dr. Aashiq Ahamed ", 0, 1, 'C')
        pdf.set_x(120)
        pdf.set_font("Arial", '', 9)
        pdf.cell(70, 5, "Chief Neurologist | ID: 88219", 0, 1, 'C')
        
        report_path = f"Report_{p_id}.pdf"
        pdf.output(report_path)
        
        st.session_state['current_report_path'] = report_path
        st.session_state['report_ready'] = True
        st.success("Report Compiled Successfully.")

    if st.session_state['report_ready']:
        with open(st.session_state['current_report_path'], "rb") as f:
            st.download_button("⬇️ DOWNLOAD PDF", f, file_name=st.session_state['current_report_path'])
            
    st.markdown("---")
    if st.button("⬅️ Back to Dashboard"):
        st.session_state['page'] = 'dashboard'
        st.rerun()

# --- MAIN ---
apply_custom_style()

if st.session_state['page'] == 'dashboard':
    show_dashboard()
elif st.session_state['page'] == 'report':
    show_report_page()